//
// Created by Ember Lee on 3/9/24.
//

#ifndef JOSHENGINE_ENGINECONFIG_H
#define JOSHENGINE_ENGINECONFIG_H

#define ENGINE_VERSION_STRING "in-dev 24w17a"

#define DEBUG_ENABLED

#define GL41_SRGB
#define METAL_SRGB
#define METAL_OS_IMGUI_THEME_SYNC

#endif //JOSHENGINE_ENGINECONFIG_H