//
// Created by Ember Lee on 3/9/24.
//

#ifndef JOSHENGINE_ENGINECONFIG_H
#define JOSHENGINE_ENGINECONFIG_H

#define ENGINE_VERSION_STRING "Pre-Alpha 2"

#define DEBUG_ENABLED

#endif //JOSHENGINE_ENGINECONFIG_H