//
// Created by Ember Lee on 3/9/24.
//

#ifndef JOSHENGINE_ENGINECONFIG_H
#define JOSHENGINE_ENGINECONFIG_H

#define ENGINE_VERSION_STRING "in-dev 24w16c"

#define DEBUG_ENABLED

#define GL41_SRGB_VK_PARITY

#endif //JOSHENGINE_ENGINECONFIG_H